### PR TITLE
Bitcoin review

### PR DESCRIPTION
**Pull request by MathyV**
Maybe create a separate commit for rebranding?
Second commit should be squashed in "Implement PoSV in protocol and blockchain. "

### CODE REVIEW

**Comment by laudney** [comment]
We need to put rebranding in a separate commit. Please convert this PR into two separate ones.

**Comment by MathyV** [comment]
They are separate commits already, just rebase them.

On December 16, 2014 12:30:21 AM GMT+01:00, Larry Ren notifications@github.com wrote:

> We need to put rebranding in a separate commit. Please Convert this PR
> into two separate ones.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/reddcoin-project/reddcoin/pull/80#issuecomment-67086616

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by laudney** [comment]
I've rebased and force-pushed.

**Comment by laudney** [comment]
Let's leave rebranding later.

**Pull request merged**
